### ISSUE TITLE
Image fails to render image/vnd.microsoft.icon

### ISSUE THREAD

**Issue by oknozor** [hecrj/iced#1078]
I am trying to render some `image/vnd.microsoft.icon` images. 

```rust
Row::new().push(
  Image::new(&icon.path)
    .height(Length::Units(32))
    .width(Length::Units(32)))
```

These are favicons fetched from various domain name : 

When rendering like this I am getting nothing for `image/vnd.microsoft.icon`. 
![image](https://user-images.githubusercontent.com/24563836/136951392-fec9ec50-4cd8-4521-969d-e9d84baf0a0a.png)

Other icon format renders as expected : 
![image](https://user-images.githubusercontent.com/24563836/136951526-d1cb4b98-d176-49cc-bee7-6bbf5f14be39.png)

iced version : 
```toml
iced = { git = "https://github.com/hecrj/iced", features = ["wgpu", "default_system_font", "palette", "svg", "image"] }
iced_native = { git = "https://github.com/hecrj/iced" }
iced_style = { git = "https://github.com/hecrj/iced" }
```
