### ISSUE TITLE
Transparency doesnt work with wgpu backend

### ISSUE THREAD

**Issue by oknozor** [hecrj/iced#596]
Seems transparency does not work on wgpu, is this normal ? 
I would happily use glow, but fonts are a bit aliased. Is there a workaround this ? 

- `features = ["wgpu", "default_system_font", "debug", "palette" ]`

<a href="https://ibb.co/H73y0tJ"><img src="https://i.ibb.co/p25Tgfm/screenshot-2020-11-05-T17-06-13-0100.png" alt="screenshot-2020-11-05-T17-06-13-0100" border="0"></a>

- `features = ["glow", "glow_default_system_font", "debug", "palette" ]`

<a href="https://ibb.co/2Kj8Kkt"><img src="https://i.ibb.co/ZThHTM8/screenshot-2020-11-05-T17-05-54-0100.png" alt="screenshot-2020-11-05-T17-05-54-0100" border="0"></a>

**Comment by myfreeweb** [comment]
See https://github.com/hecrj/iced/pull/371 / https://github.com/gfx-rs/wgpu/issues/687

tl;dr for now wgpu hardcodes opaque mode, so it needs to be patched. You can use my fork:

```toml
[patch.crates-io]
# patch: transparency (config.composite_alpha_mode = hal::window::CompositeAlphaMode::PREMULTIPLIED)
wgpu-core  = { git = "https://github.com/myfreeweb/wgpu", branch = "v0.6-alpha" }
wgpu-types = { git = "https://github.com/myfreeweb/wgpu", branch = "v0.6-alpha" }
```
