### ISSUE TITLE
git URLs for iced_native and iced_graphics

### ISSUE THREAD

**Issue by edko99** [hecrj/iced#705]
I am using 

`iced = {git = "https://github.com/hecrj/iced.git", features = ["image", "svg", "canvas", "tokio", "debug"]}`

in my `Cargo.toml`, to make sure I have the latest version, and all examples compile.

However, I don't know how to specify the git URLs for `iced_native` and `iced_graphics`. Is this possible?

**Comment by yusdacra** [comment]
```toml
iced = { git = "https://github.com/hecrj/iced", features = ["tokio", "image", "svg", "canvas", "debug"] }
iced_native = { git = "https://github.com/hecrj/iced" }
iced_graphics = { git = "https://github.com/hecrj/iced" }
```

You can do it like this, since `iced_native` and `iced_graphics` are packages too.
